version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - chat_server_env=product
    volumes:
      - .:/home/app/web

    networks:
      - db
      - app
networks:
  db:
    external: true
  app:
    external: true
