version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/chat_server
    volumes:
      - .:/home/app/web
    depends_on:
      - db
  db:
    build: postgres
    image: chat_server_postgres-13-alpine-multi-user
    volumes:
      - $HOME/.postgres/chat_server_db/data/postgresql:/var/lib/postgresql/data
    ports:
      - 5435:5432
    environment:
      - POSTGRES_DBS=chat_server, chat_server_test
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
