[default]

[default.server]
port = "8080"
host = "0.0.0.0"
debug = false
cors_origins = ["*"]

[default.db]
name = "chat"
host = "127.0.0.1"
port = 27017
user = "root"
password = "root"
uri = "@jinja mongodb://{{ this.db.user }}:{{ this.db.password }}@{{ this.db.host }}:{{ this.db.port }}/{{ this.db.name }}"