# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  linter:
    strategy:
      fail-fast: false
      matrix:
        python-version: [ 3.9 ]
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    environment: production
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # 读取完整历史,如果不是0则读取最新的
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: download wheels
        run: |
          pip install wheel
          pip wheel --no-cache-dir --wheel-dir ./wheels -r requirements.txt
          zip -r wheels.zip wheels
      - name: copy to machine
        uses: wlixcc/SFTP-Deploy-Action@v1.0
        with:
          username: ${{ secrets.TENCENT_CE_LGQ5_LOGINNAME}}
          server: ${{ secrets.TENCENT_CE_LGQ5_IP }}
          ssh_private_key: ${{ secrets.TENCENT_CE_LGQ5 }}
          local_path: ./wheels.zip
          remote_path: ${{ secrets.ROMATE_PATH }}/chat-server
      - name: unzip # 在服务器端解压代码
        uses: appleboy/ssh-action@master
        with:
          key: ${{ secrets.TENCENT_CE_LGQ5 }}
          host: ${{ secrets.TENCENT_CE_LGQ5_IP }}
          username: ${{ secrets.TENCENT_CE_LGQ5_LOGINNAME}}
          script: |
            cd ${{ secrets.ROMATE_PATH }}/chat-server
            rm -rf wheels
            unzip wheels.zip
      - name: update to tencent # 将代码自动部署到服务端
        uses: appleboy/ssh-action@master
        with:
          key: ${{ secrets.TENCENT_CE_LGQ5 }}
          host: ${{ secrets.TENCENT_CE_LGQ5_IP }}
          username: ${{ secrets.TENCENT_CE_LGQ5_LOGINNAME}}
          script: |
            cd ${{ secrets.ROMATE_PATH }}/chat-server
            git pull origin main
            sudo docker-compose up -d
            sudo docker-compose restart