# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  linter:
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.10]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    environment: production
    steps:
      - name: update to tencent # 将代码自动部署到服务端
        uses: appleboy/ssh-action@master
        with:
          key: ${{ secrets.TENCENT_CE_LGQ5 }}
          host: ${{ secrets.TENCENT_CE_LGQ5_IP }}
          username: ${{ secrets.TENCENT_CE_LGQ5_LOGINNAME}}
          script: |
            cd ${{ secrets.ROMATE_PATH }}/chat-server
            git pull origin master
            sudo docker-compose up -d
            sudo docker-compose restart